# This is a basic workflow to help you get started with Actions

name: CI / CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - solutions/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: packed-solutions/con_core.zip
          solution-folder: solutions/con_core/src
          solution-type: Both
      - uses: actions/upload-artifact@v3
        with:
          path: packed-solutions
          name: packed-solutions
  deploy:
    environment: production
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packed-solutions
      - name: Import con_core
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: con_core_managed.zip
      - name: Import con_admissions
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: con_admissions_managed.zip
