# This is a basic workflow to help you get started with Actions

name: Commit Admissions

# Controls when the workflow will run
on:
  push:
    paths:
      - solutions/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      message:
        default: Automated commit
        description: Message for the commit
        required: true

jobs:
  export-unpack-commit:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - uses: ./.github/actions/export-unpack-commit
        with:
          message: ${{ github.event.inputs.message }}
          environment-url: ${{ secrets.URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: con_admissions
